name: My First Workflow
on: 
    workflow_dispatch: # manual trigger
jobs:
    job-name-1:
        # where the job will be run - agent/runner
        # github hosted runners -> ubuntu, windows, macos
        runs-on: ubuntu-latest
        steps:
            # mention what will be installed/executed on the runner VM
            - name: Run simple command
              run: echo "This is step 1"
            - name: Run multiple commands
              run: |
                mkdir mydemo
                cd mydemo
                echo "This file is on runner VM" > demo.txt
                echo "This is step 2"
